excluded:
    - Build
    - Pods

disabled_rules:
    - file_length
    - type_body_length
    - line_length
    - nesting

opt_in_rules:
    - attributes
    - closure_end_indentation
    - closure_spacing
    - conditional_returns_on_newline
    - empty_count
    - explicit_init
    - extension_access_modifier
    - fatal_error_message
    - first_where
    - force_unwrapping
    - implicit_return
    - joined_default_parameter
    - let_var_whitespace
    - multiline_parameters
    - nimble_operator
    - no_extension_access_modifier
    - number_separator
    - object_literal
    - operator_usage_whitespace
    - overridden_super_call
    - pattern_matching_keywords
    - prohibited_super_call
    - quick_discouraged_call
    - redundant_nil_coalescing
    - single_test_class
    - sorted_imports
    - switch_case_on_newline
    - trailing_closure
    - unneeded_parentheses_in_closure_argument
    - vertical_parameter_alignment_on_call
