platform :ios, '10.0'

target 'Saturn' do

  use_frameworks!

  pod 'FacebookCore', '~> 0.2.0'
  pod 'FacebookLogin', '~> 0.2.0'
  pod 'FeedKit', '~> 7.0.0'
  pod 'SDWebImage', '~> 4.1.0'
  pod 'SwiftLint', '~> 0.22.0'
  pod 'TwitterKit', '~> 3.1.0'
  pod "youtube-ios-player-helper", "~> 0.1.0"

  target 'SaturnTests' do
    inherit! :search_paths
  end

end
