platform :ios, '10.0'

target 'Saturn' do

  use_frameworks!

  pod 'Pastel', '~> 0.3.0'
  pod 'SwiftLint', '~> 0.19.0'
  pod 'TwitterKit', '~> 3.0.0'
  pod 'FacebookCore', '~> 0.2.0'
  pod 'FacebookLogin', '~> 0.2.0'

  target 'SaturnTests' do
    inherit! :search_paths
  end

end
